services:
  atuin:
    image: ghcr.io/atuinsh/atuin:v18.13.3
    command: start
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./config:/config
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_DB_URI: postgres://${POSTGRES_USER:-atuin}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-db}:5432/${POSTGRES_DB:-atuin}
      ATUIN_CONFIG_DIR: /config
      RUST_LOG: info,atuin_server=debug
